name: Build

on:
    pull_request:
        branches: 
            - master
    workflow_dispatch:

permissions:
  pull-requests: write

jobs:
    build:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
                submodules: true

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
       
        - name: Extract branch name
          shell: bash
          run: echo "BR_PROJECT=$(TMP=${{github.event.pull_request.title}};echo ${TMP##*/})" >> "$GITHUB_OUTPUT"
          id: extract_branch
                
        - name: Publish ${{ steps.extract_branch.outputs.BR_PROJECT }} Addon
          uses: home-assistant/builder@master
          env:
                CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
          with:
                args: |
                    --all \
                    --target ${{ steps.extract_branch.outputs.BR_PROJECT }} \
                    --docker-hub dianlight
