name: Build

on:
    pull_request:
        branches: 
            - master
    workflow_dispatch:

permissions:
  pull-requests: write

jobs:
    build:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
                submodules: true

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: echo "$JOB_CONTEXT"
        - name: Dump steps context
          env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
          run: echo "$STEPS_CONTEXT"
        - name: Dump runner context
          env:
            RUNNER_CONTEXT: ${{ toJson(runner) }}
          run: echo "$RUNNER_CONTEXT"
        - name: Dump strategy context
          env:
            STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          run: echo "$STRATEGY_CONTEXT"
        - name: Dump matrix context
          env:
            MATRIX_CONTEXT: ${{ toJson(matrix) }}
          run: echo "$MATRIX_CONTEXT"

        - name: Extract branch name
          shell: bash
          run: echo "BR_PROJECT=$(TMP=${{github.head_ref}};echo ${TMP##*/})" >> "$GITHUB_OUTPUT"
          id: extract_branch
                
        - name: Publish ${{ steps.extract_branch.outputs.BR_PROJECT }} Addon
          uses: home-assistant/builder@master
          env:
                CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
          with:
                args: |
                    --all \
                    --target ${{ steps.extract_branch.outputs.BR_PROJECT }} \
                    --docker-hub dianlight
