name: Docker Image CI - Build Pre-Release.

on:
  push:
    branches:
      - prerelease/*
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish SambaNAS Addon
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --target sambanas \
            --docker-hub dianlight

      - name: Extract branch name
        shell: bash
#        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        run: echo "{branch}=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: pull-request
        run: |
          gh codespace create -b "release/${{ steps.extract_branch.outputs.branch }}" 
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --base "release/${{ steps.extract_branch.outputs.branch }}" --title "Releasing ${{ github.ref }} into release" --body ":crown: *An automated PR*"          
#        uses: repo-sync/pull-request@v2
#        continue-on-error: true
#        with:
#          destination_branch: "release/${{ steps.extract_branch.outputs.branch }}"
#          pr_title: "Releasing ${{ github.ref }} into master"
#          pr_body: ":crown: *An automated PR*"
#          github_token: ${{ secrets.GITHUB_TOKEN }}
