name: Docker Image CI - Build Pre-Release.

on:
  push:
    branches:
      - prerelease/*
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish SambaNAS Addon
        if: ${{ false }}
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --target sambanas \
            --docker-hub dianlight

      - name: Extract branch name
        shell: bash
        run: echo "BR_VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
        id: extract_branch

      - name: create-branch
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ steps.extract_branch.outputs.BR_VERSION }}"
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b  "release/${GITHUB_REF##*/}"

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.extract_branch.outputs.BR_VERSION }}

      - name: pull-request
        shell: bash
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --base "release/${GITHUB_REF##*/}" --title "Releasing ${{ github.ref }} into release" --body ":crown: *An automated PR*"
