name: Docker Image CI - Build Pre-Release.

on:
  push:
    branches:
      - prerelease/*
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish SambaNAS Addon
        if: ${{ false }}
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --target sambanas \
            --docker-hub dianlight

      - name: Extract branch name
        shell: bash
        run: echo "BR_VERSION=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
        id: extract_branch

      - name: pull-request
        continue-on-error: true
        shell: bash
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --base "release/${{ steps.extract_branch.outputs.BR_VERSION }}" --title "Releasing ${{ github.ref }} into prerelease" --body ":crown: *An automated PR*"
