name: Docker Image CI - Build Release.

on:
  push:
    branches: 
      - release/* 
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - shell: bash
        id: build
        run: |
          export CAS_API_KEY=${{ secrets.CAS_API_KEY }}
          export SIGNER_ID=${{ secrets.SIGNER_ID }}
          env > "${{ runner.temp }}/env_file"
          sed -i "/\(HOME\|TERM\|PWD\|HOSTNAME\|PATH\|SHLVL\|USER\|GOROOT\)/d" "${{ runner.temp }}/env_file"

      - name: Publish Plex Addon
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target addon-plex/plex \
            --docker-hub dianlight     

      - name: Publish SambaNAS Addon
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target sambanas \
            --docker-hub dianlight 
            --env-file "${{ runner.temp }}/env_file" \

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}       
